language: scala
sudo: false
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
  - 2.13.0-M1
jdk:
  - oraclejdk7
  - oraclejdk8
script: sbt ++${TRAVIS_SCALA_VERSION} test publishLocal
matrix:
  exclude:
  - scala: 2.12.2
    jdk: oraclejdk7
  - scala: 2.13.0-M1
    jdk: oraclejdk7
